name: Browser Test Build
on: push
jobs:
  cypress-run:
    runs-on: Mac
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: firerfox