name: Regression End-to-End Tests

on: push

jobs:
  cypress-run:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run All Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run allTest

      - name: Uploading artifact  
        uses: actions/upload-artifact@v4  
        if: always()  
        with:    
          name: cypress-execution-report    
          path: cypress/reports    
          retention-days: 7

      - name: Send Slack Notification on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
              "attachments": [
                  {
                      "fallback": "Cypress Tests Passed Successfully",
                      "color": "good",
                      "title": "Regression End-to-End Tests Status: SUCCESS",
                      "text": "Regression End-to-End Tests have passed successfully.",
                      "footer": "GitHub Actions",
                      "ts": '"$(date +%s)"'
                  }
              ]
          }' \
          ${{ secrets.SLACK_WEBHOOK }}

      - name: Send Slack Notification on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
              "attachments": [
                  {
                      "fallback": "Cypress Tests Failed",
                      "color": "danger",
                      "title": "Regression End-to-End Tests Status: FAILURE",
                      "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "text": "Regression End-to-End Tests have failed. Please review the logs.",
                      "footer": "GitHub Actions",
                      "ts": '"$(date +%s)"'
                  }
              ]
          }' \
          ${{ secrets.SLACK_WEBHOOK }}
