name: Regression End-to-End Tests

on: push

jobs:
  cypress-run:
    runs-on: Ubantu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run allTest

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
        
         SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
         SLACK_ICON: https://github.com/rtCamp.png?size=48
         SLACK_MESSAGE: 'Automation Test Report https://github.com/mehulraninga13/M-Aug-24-Cypress/actions/runs/${{github.run_id}}'
         SLACK_TITLE: Cypress Automation 
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}