name: Multiple Jobs - On Demand Job

on: 
  workflow_dispatch:

jobs:
  Add-To-Cart-run:
    runs-on: Ubantu-latest # Correct MacOS runner syntax

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ensure the correct version of Node.js is installed

      - name: Install dependencies
        run: npm install

      - name: Cypress run - Add to Cart
        uses: cypress-io/github-action@v6
        with:
          command: npm run addToCart # Make sure this script exists in your package.json

      - name: Cypress Test Report - Add to Cart
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Add to Cart
          path: cypress/reports/html # Ensure this path matches where the Mochawesome report is generated

  Reg-Flow-run:
    runs-on: Ubantu-latest # Use the same MacOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Same Node.js version setup

      - name: Install dependencies
        run: npm install

      - name: Cypress run - Registration Flow
        uses: cypress-io/github-action@v6
        with:
          command: npm run registerFlow # Ensure this script is present in your package.json

      - name: Cypress Test Report - Registration Flow
        if: always() # Upload the artifact even if the test fails
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Reg Flow
          path: cypress/reports/html # Same path to your generated report